language: php
php:
  - '5.6'
  - '7.0'
services:
  - mysql
before_install:
  - mysql -e "create database IF NOT EXISTS ALUC;" -u root
install:
  - composer install
  - composer dump-autoload
before_script:
  - mysqladmin -u root password 'root1234'
script:
  - phpunit
