language: php
php:
  - '5.6'
  - '7.0'
services:
  - mysql
before_install:
  - sudo echo 'US/Eastern' >/etc/timezone
  - sudo apt-get install --reinstall tzdata
install:
  - composer install
  - composer dump-autoload
before_script:
  - mysql -e "create database IF NOT EXISTS ALUC;" -u root
  - mysql -u root ALUC < database/DDL.sql
  - mysql -u root ALUC < database/populate.sql
  - mysqladmin -u root password '1234'
script:
  - make test
